/* ============================================================================
   SHAFTOLOGY — Aftermarket Driver Shaft Database
   ----------------------------------------------------------------------------
   Lineups reflect models current as of the 2026 season (researched from
   manufacturer + retailer sources, June 2026). Profile fields are RELATIVE
   1–5 scales unless noted — directional fitting characteristics for
   comparison, NOT exact OEM lab numbers:

     launch      1 = very low ............ 5 = very high
     spin        1 = very low ............ 5 = very high
     tip         tip stiffness  1 = active/soft ... 5 = stout/boardy
     mid         mid stiffness  1 = soft .......... 5 = firm
     butt        handle stiffness 1 = soft ........ 5 = firm
     balance     1 = tip-heavy .......... 5 = counterbalanced (butt-heavy)
     feel        1 = boardy/harsh ....... 5 = smooth/buttery
     stability   1 = whippy ............. 5 = rock-solid (low torque feel)
     torque      approx degrees @ ~6S (lower = more stable)

   weights = available class weights (g). flexes = available flexes.
   ========================================================================== */

const SHAFTS = [
  /* ================================ FUJIKURA ============================== */
  { id:'fuji-ventus-blue', mfr:'Fujikura', series:'Ventus', model:'Ventus Blue', gen:'VeloCore+', year:2025,
    weights:[50,60,70,80], flexes:['R','S','X','TX'], price:375,
    launch:3, spin:2, torque:3.1, tip:4, mid:3, butt:3, balance:3, feel:3, stability:5,
    tags:['Mid launch','Low-mid spin','Stable tip'],
    bestFor:'Players wanting a stable mid-launch profile that holds up under speed.',
    blurb:'The benchmark all-rounder, now on VeloCore+. The added premium bias-core material tightens dispersion and adds ball speed while keeping the trusted stable mid flight.' },
  { id:'fuji-ventus-black', mfr:'Fujikura', series:'Ventus', model:'Ventus Black', gen:'VeloCore+', year:2025,
    weights:[60,70,80], flexes:['S','X','TX'], price:375,
    launch:2, spin:1, torque:2.9, tip:5, mid:4, butt:4, balance:2, feel:2, stability:5,
    tags:['Low launch','Low spin','Stout tip'],
    bestFor:'High-speed, aggressive transitions chasing the lowest spin.',
    blurb:'The stoutest of the family and the shaft trusted by every 2025 men\'s major champion. A genuinely firm tip and handle for hard loaders who want to flatten the window.' },
  { id:'fuji-ventus-red', mfr:'Fujikura', series:'Ventus', model:'Ventus Red', gen:'VeloCore+', year:2025,
    weights:[50,60,70], flexes:['R','S','X'], price:375,
    launch:4, spin:3, torque:3.6, tip:3, mid:3, butt:2, balance:4, feel:4, stability:4,
    tags:['Mid-high launch','Counterbalanced','Active tip'],
    bestFor:'Smoother tempos who want help launching it with a counterbalanced feel.',
    blurb:'The launch-friendly sibling. A softer handle and counterbalanced build add ramp to the flight while VeloCore+ keeps the tip respectable.' },
  { id:'fuji-ventus-white', mfr:'Fujikura', series:'Ventus', model:'Ventus White', gen:'VeloCore+', year:2025,
    weights:[40,50], flexes:['R2','R','S'], price:375,
    launch:4, spin:3, torque:4.0, tip:3, mid:3, butt:3, balance:3, feel:4, stability:3,
    tags:['Lightweight','High launch','Mid-high spin'],
    bestFor:'Speed-seekers who want easy launch in a sub-50g Ventus build.',
    blurb:'The newest profile of 2025 — VeloCore+ in an ultralight (~50g) package. Per Fujikura\'s own spec chart it flies HIGH with mid-high spin, rounding out the line below the heavier Blue/Black/Red.' },
  { id:'fuji-ventus-tr-blue', mfr:'Fujikura', series:'Ventus', model:'Ventus TR Blue', gen:'VeloCore+', year:2026,
    weights:[50,60,70], flexes:['S','X','TX'], price:400,
    launch:3, spin:2, torque:3.0, tip:4, mid:4, butt:3, balance:3, feel:3, stability:5,
    tags:['Mid launch','Lower spin','Tour Spec'],
    bestFor:'Ventus Blue lovers who want firmer mid-section and tighter spin.',
    blurb:'The 2026 Tour Spec evolution. VeloCore+ paired with Spread Tow fabric reinforces the mid-section for greater stability, a more refined feel, and more speed through impact.' },
  { id:'fuji-ventus-tr-black', mfr:'Fujikura', series:'Ventus', model:'Ventus TR Black', gen:'VeloCore+', year:2026,
    weights:[60,70,80], flexes:['X','TX'], price:400,
    launch:1, spin:1, torque:2.8, tip:5, mid:5, butt:4, balance:2, feel:2, stability:5,
    tags:['Very low launch','Very low spin','Boardy'],
    bestFor:'Elite speed delivering huge load that needs the flattest flight.',
    blurb:'The firmest shaft Fujikura builds for 2026. VeloCore+ plus Spread Tow in the most stout TR profile — minimal launch, minimal spin, maximum stability.' },
  { id:'fuji-speeder-nx-blue', mfr:'Fujikura', series:'Speeder', model:'Speeder NX Blue', gen:'VTC', year:2024,
    weights:[50,60,70], flexes:['R','S','X'], price:350,
    launch:3, spin:3, torque:3.5, tip:3, mid:3, butt:3, balance:3, feel:4, stability:3,
    tags:['Mid launch','Mid spin','Smooth'],
    bestFor:'Tempos that want classic Speeder rhythm with a mid profile.',
    blurb:'Variable Torque Core tunes stiffness along the shaft for the signature smooth, rhythmic Speeder load in a balanced mid-launch package.' },
  { id:'fuji-speeder-nx-green', mfr:'Fujikura', series:'Speeder', model:'Speeder NX Green', gen:'VTC', year:2024,
    weights:[50,60,70], flexes:['R','S','X','TX'], price:350,
    launch:3, spin:2, torque:3.3, tip:4, mid:3, butt:3, balance:3, feel:3, stability:4,
    tags:['Mid launch','Low spin','Stable'],
    bestFor:'Players wanting low spin without going fully stout.',
    blurb:'A spin-killer that still feels lively. Variable Torque Core keeps it stable through the strike with a smoother load than the boards.' },
  { id:'fuji-speeder-nx-violet', mfr:'Fujikura', series:'Speeder', model:'Speeder NX Violet', gen:'VTC · DHX', year:2026,
    weights:[40,50,60], flexes:['R','S','X'], price:375,
    launch:3, spin:3, torque:3.6, tip:3, mid:2, butt:3, balance:4, feel:5, stability:3,
    tags:['Speed-biased','Mid launch','Smooth'],
    bestFor:'Players hunting clubhead speed from a smooth, active profile.',
    blurb:'New for 2026. Built on the NX Blue profile with breakthrough DHX technology to maximize clubhead speed — a lively, smooth-loading shaft for distance.' },

  /* =============================== MITSUBISHI ============================= */
  { id:'mitsu-diamana-wb', mfr:'Mitsubishi', series:'Diamana', model:'Diamana WB', gen:'6th Gen', year:2025,
    weights:[50,60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:2, torque:3.1, tip:4, mid:5, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Firm mid'],
    bestFor:'Strong players wanting the firm-mid white-board flight.',
    blurb:'The firm-mid profile of the 6th-generation Diamana. Xlink Tech resin drives carbon volume up for better feel while the stiff mid flattens the window for fast swings.' },
  { id:'mitsu-diamana-rb', mfr:'Mitsubishi', series:'Diamana', model:'Diamana RB', gen:'6th Gen', year:2025,
    weights:[50,60,70], flexes:['R','S','X'], price:400,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:4, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','Energy butt'],
    bestFor:'The neutral, do-everything 6th-gen Diamana fitting.',
    blurb:'The neutral-mid profile. 80-Ton Dialead pitch fiber in the butt drives maximum energy transfer, giving a smooth but efficient mid/mid flight.' },
  { id:'mitsu-diamana-bb', mfr:'Mitsubishi', series:'Diamana', model:'Diamana BB', gen:'6th Gen', year:2025,
    weights:[40,50,60,70], flexes:['R','S','X'], price:400,
    launch:4, spin:3, torque:3.6, tip:3, mid:2, butt:3, balance:3, feel:5, stability:3,
    tags:['Mid-high launch','Mid spin','Soft mid'],
    bestFor:'Smoother tempos wanting easy launch and signature Diamana feel.',
    blurb:'The soft-mid, blue-board-style member of the 6th generation. An easy, high-launching load defined by that silky, connected Diamana feel.' },
  { id:'mitsu-tensei-1k-white', mfr:'Mitsubishi', series:'Tensei', model:'Tensei 1K Pro White', gen:'1K', year:2023,
    weights:[60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:2, torque:3.1, tip:5, mid:4, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Premium stout'],
    bestFor:'High-speed players wanting a premium, very stable low-launch build.',
    blurb:'1K carbon weave wraps a genuinely stout profile — firm tip to handle with exceptional hoop strength and stability for the strongest swings.' },
  { id:'mitsu-tensei-1k-blue', mfr:'Mitsubishi', series:'Tensei', model:'Tensei 1K Pro Blue', gen:'1K', year:2023,
    weights:[50,60,70], flexes:['R','S','X'], price:400,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','All-around'],
    bestFor:'A smooth, neutral mid profile with premium 1K feel.',
    blurb:'The neutral 1K profile. A smooth-loading mid/mid build with the dampened, premium feel of the 1K carbon handle.' },
  { id:'mitsu-kaili-white', mfr:'Mitsubishi', series:"Kai'li", model:"Kai'li White", gen:"Kai'li", year:2023,
    weights:[60,70,80], flexes:['S','X','TX'], price:375,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:3, balance:3, feel:3, stability:5,
    tags:['Low launch','Low spin','Stable'],
    bestFor:'Players chasing a stable, low-launch tour profile.',
    blurb:'The low-launch, low-spin member of the Kai\'li line — firm and quiet through impact for stronger players.' },
  { id:'mitsu-kaili-blue', mfr:'Mitsubishi', series:"Kai'li", model:"Kai'li Blue", gen:"Kai'li", year:2023,
    weights:[50,60,70], flexes:['R','S','X'], price:375,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:3,
    tags:['Mid launch','Mid spin','Smooth'],
    bestFor:'A neutral, smooth mid profile for a wide range of speeds.',
    blurb:'The balanced, smooth-loading mid/mid option — the versatile middle child of the Kai\'li family.' },
  { id:'mitsu-kaili-red', mfr:'Mitsubishi', series:"Kai'li", model:"Kai'li Red", gen:"Kai'li", year:2024,
    weights:[40,50,60], flexes:['R','S','X'], price:375,
    launch:4, spin:3, torque:3.6, tip:2, mid:3, butt:3, balance:4, feel:4, stability:3,
    tags:['High launch','Mid spin','Counterbalanced'],
    bestFor:'Moderate tempos wanting added height and carry.',
    blurb:'The high-launch Kai\'li. A softer, more active tip and counterbalanced build add easy height for moderate swing speeds.' },
  { id:'mitsu-vanquish-green', mfr:'Mitsubishi', series:'Vanquish', model:'Vanquish Green', gen:'Vanquish', year:2024,
    weights:[40,50], flexes:['R','S'], price:300,
    launch:5, spin:4, torque:4.2, tip:2, mid:2, butt:2, balance:4, feel:5, stability:2,
    tags:['Ultralight','High launch','Smooth'],
    bestFor:'Moderate and slower swing speeds needing speed and height.',
    blurb:'An ultralight, high-launch profile built to add clubhead speed and carry for moderate tempos.' },

  /* ============================ GRAPHITE DESIGN ========================== */
  { id:'gd-ad-vr', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD VR', gen:'VR', year:2024,
    weights:[40,50,60,70,80], flexes:['R2','R1','SR','S','X'], price:450,
    launch:4, spin:2, torque:3.3, tip:4, mid:4, butt:4, balance:3, feel:4, stability:4,
    tags:['Mid-high launch','Low spin','Firm overall'],
    bestFor:'Players wanting mid-high launch with genuinely low spin.',
    blurb:'"Vanquish all Rivals." Firm-to-stiff from the handle through a medium/firm center to a firm tip — a rare combination of mid-high launch with low spin.' },
  { id:'gd-ad-cq', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD CQ', gen:'CQ', year:2024,
    weights:[40,50,60,70], flexes:['R','SR','S','X'], price:450,
    launch:4, spin:3, torque:3.4, tip:3, mid:3, butt:3, balance:3, feel:5, stability:4,
    tags:['Mid-high launch','Controlled spin','Smooth'],
    bestFor:'Players wanting easy launch with stability and a smooth feel.',
    blurb:'Built with Graphite Design\'s Material Stiffness Integration process and aerospace-grade carbon for torsional resistance — mid-to-high launch with controlled, repeatable spin.' },
  { id:'gd-ad-di', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD DI', gen:'DI', year:2019,
    weights:[50,60,70,80], flexes:['R','S','X','TX'], price:400,
    launch:3, spin:3, torque:3.3, tip:4, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','Firm tip'],
    bestFor:'The timeless tour profile that flatters almost everyone.',
    blurb:'Arguably the most successful aftermarket profile ever. A firm tip with a smooth overall load — mid/mid with rock-steady dispersion.' },
  { id:'gd-ad-iz', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD IZ', gen:'IZ', year:2018,
    weights:[50,60,70,80], flexes:['R','S','X','TX'], price:400,
    launch:3, spin:2, torque:3.2, tip:4, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Low-mid spin','Stable impact'],
    bestFor:'DI fans who want a touch lower spin and a firmer mid-strike.',
    blurb:'A more stable-through-impact DI variant. Holds the face square at speed with slightly tighter spin numbers.' },
  { id:'gd-ad-xc', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD XC', gen:'XC', year:2020,
    weights:[50,60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:4, balance:2, feel:3, stability:5,
    tags:['Low-mid launch','Low spin','Firm tip & handle'],
    bestFor:'Strong transitions wanting firm tip plus a firm handle.',
    blurb:'Firm in both the tip and the butt — a double-stiff profile that rewards aggressive, fast players with low spin and tight dispersion.' },
  { id:'gd-ad-vf', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD VF', gen:'VF', year:2021,
    weights:[50,60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:1, torque:3.0, tip:4, mid:5, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Very low spin','Stiff mid'],
    bestFor:'Players who deliver a lot of load and need a firm mid-section.',
    blurb:'A uniquely firm mid-section defines the VF. It resists ballooning for hard swingers and produces a flat, low-spin window.' },
  { id:'gd-ad-ub', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD UB', gen:'UB', year:2022,
    weights:[40,50,60,70], flexes:['R','S','X'], price:400,
    launch:4, spin:3, torque:3.5, tip:3, mid:2, butt:3, balance:3, feel:5, stability:3,
    tags:['Mid-high launch','Mid spin','Smooth mid'],
    bestFor:'Smoother tempos wanting easy launch and a buttery mid.',
    blurb:'A softer mid-section gives the UB an easy, high-launching load with the signature Graphite Design smoothness.' },
  { id:'gd-ad-gp', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD GP', gen:'GP', year:2017,
    weights:[40,50,60,70], flexes:['R','S','X'], price:400,
    launch:5, spin:4, torque:3.7, tip:2, mid:3, butt:2, balance:4, feel:5, stability:3,
    tags:['High launch','High spin','Easy load'],
    bestFor:'Moderate speeds needing maximum carry and a soft tip.',
    blurb:'The launch monster of the line. A softer tip and counterbalanced build add height and carry for moderate swing speeds.' },

  /* =============================== PROJECT X ============================= */
  { id:'px-denali-black', mfr:'Project X', series:'Denali', model:'Denali Frost Black', gen:'Frost G2', year:2025,
    weights:[60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:3, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Stable'],
    bestFor:'Fast players wanting a modern, refined low-launch build.',
    blurb:'The low-launch Frost. Second-gen Denali with Focused Rotational Stability tech for tighter dispersion and a smooth, controlled, quiet flight.' },
  { id:'px-denali-blue', mfr:'Project X', series:'Denali', model:'Denali Frost Blue', gen:'Frost G2', year:2025,
    weights:[50,60,70], flexes:['R','S','X'], price:400,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','Smooth'],
    bestFor:'The neutral, do-everything Denali fitting.',
    blurb:'The mid/mid Frost. Focused Rotational Stability tech adds off-center stability to a smooth, neutral profile that suits the widest range of players.' },
  { id:'px-denali-red', mfr:'Project X', series:'Denali', model:'Denali Frost Red', gen:'Frost G2', year:2025,
    weights:[40,50,60], flexes:['R','S','X'], price:400,
    launch:4, spin:4, torque:3.8, tip:2, mid:3, butt:2, balance:4, feel:4, stability:3,
    tags:['High launch','Higher spin','Counterbalanced'],
    bestFor:'Moderate speeds prioritizing carry and an easy load.',
    blurb:'The launch-and-carry Frost. A soft tip and counterbalanced build make it one of the easiest premium shafts to elevate.' },
  { id:'px-hzrdus-black-g5', mfr:'Project X', series:'HZRDUS', model:'HZRDUS Black Gen 5', gen:'Gen 5', year:2024,
    weights:[60,70], flexes:['S','X','TX'], price:300,
    launch:2, spin:1, torque:3.0, tip:4, mid:4, butt:4, balance:2, feel:2, stability:5,
    tags:['Low launch','Very low spin','Boardy'],
    bestFor:'Tour-level speed chasing the lowest spin and flattest flight.',
    blurb:'A modern carbon weave in the mid-section stiffens the shaft where it sees the most stress — low torque, low spin, tour-level stability.' },
  { id:'px-hzrdus-blue-g5', mfr:'Project X', series:'HZRDUS', model:'HZRDUS Blue Gen 5', gen:'Gen 5', year:2024,
    weights:[50,60,70], flexes:['S','X'], price:250,
    launch:3, spin:2, torque:3.3, tip:4, mid:3, butt:3, balance:3, feel:3, stability:4,
    tags:['Mid launch','Low-mid spin','Stout tip'],
    bestFor:'Players wanting a stout tip in a more accessible package.',
    blurb:'A stout-tipped, mid-launch, low-spin workhorse with Gen 5 mid-section stability — a lot of control at a friendly price.' },

  /* ================================= ALDILA ============================== */
  { id:'aldila-rogue-white', mfr:'Aldila', series:'Rogue', model:'Rogue White 130 MSI', gen:'Reissue', year:2024,
    weights:[60,70,80], flexes:['S','X','TX'], price:275,
    launch:2, spin:1, torque:3.0, tip:5, mid:4, butt:4, balance:2, feel:2, stability:5,
    tags:['Low launch','Very low spin','Ultra-stout'],
    bestFor:'The hardest swingers who want a true boardy, low-spin profile.',
    blurb:'Reissued with 130 MSI prepreg in the tip — one of the stoutest profiles available. A low-launch, low-spin board for elite speed.' },
  { id:'aldila-quaranta', mfr:'Aldila', series:'Quaranta', model:'Aldila Quaranta', gen:'Quaranta', year:2026,
    weights:[40,50], flexes:['A','R','S'], price:225,
    launch:5, spin:4, torque:4.3, tip:2, mid:2, butt:2, balance:4, feel:5, stability:2,
    tags:['Ultralight','High launch','Smooth'],
    bestFor:'Slower and moderate swing speeds chasing speed and height.',
    blurb:'A featherweight, high-launch profile in the spirit of the old ultralight boards — built to add clubhead speed for moderate and slower tempos.' },

  /* ============================== UST MAMIYA ============================= */
  { id:'ust-elements-earth', mfr:'UST Mamiya', series:'Elements', model:'Elements Earth', gen:'Elements', year:2025,
    weights:[60,70,80], flexes:['S','X'], price:375,
    launch:2, spin:2, torque:3.1, tip:5, mid:4, butt:3, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Stiff tip'],
    bestFor:'Strong players wanting a firm tip and a flatter window.',
    blurb:'The low-launch Element. UST\'s research-led design prioritizes tip stiffness, delivering a penetrating, low-spinning flight with consistent profiles weight to weight.' },
  { id:'ust-elements-fire', mfr:'UST Mamiya', series:'Elements', model:'Elements Fire', gen:'Elements', year:2025,
    weights:[50,60,70], flexes:['R','S','X'], price:375,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','All-around'],
    bestFor:'The neutral, broadly fittable Elements profile.',
    blurb:'The mid-launch Element. A smooth, neutral mid/mid profile with the consistent flex-to-flex behavior that defines the Elements line.' },
  { id:'ust-elements-wind', mfr:'UST Mamiya', series:'Elements', model:'Elements Wind', gen:'Elements', year:2025,
    weights:[40,50,60], flexes:['R','S'], price:375,
    launch:4, spin:4, torque:3.7, tip:2, mid:3, butt:2, balance:4, feel:4, stability:3,
    tags:['High launch','Higher spin','Easy'],
    bestFor:'Moderate tempos prioritizing carry and an easy load.',
    blurb:'The high-launch Element. A softer, more active tip and lighter build make it the easiest of the line to elevate.' },
  { id:'ust-linq-blue', mfr:'UST Mamiya', series:'LIN-Q', model:'LIN-Q M40X Blue', gen:'M40X', year:2022,
    weights:[50,60,70], flexes:['R','S','X','TX'], price:350,
    launch:3, spin:2, torque:3.2, tip:4, mid:3, butt:3, balance:3, feel:3, stability:4,
    tags:['Mid launch','Low spin','Stable'],
    bestFor:'Players wanting a stable, low-spin mid profile.',
    blurb:'M40X carbon delivers a stable, mid-launch, low-spin profile — a quietly excellent tour option that flies under the radar.' },
  { id:'ust-helium', mfr:'UST Mamiya', series:'Helium', model:'Helium Nanocore', gen:'Nanocore', year:2020,
    weights:[40,50,60], flexes:['A','R','S'], price:175,
    launch:5, spin:4, torque:4.3, tip:2, mid:2, butt:2, balance:4, feel:5, stability:2,
    tags:['Ultralight','High launch','High spin'],
    bestFor:'Moderate and senior swing speeds needing speed and height.',
    blurb:'An ultralight, high-launch profile built to add clubhead speed and carry for moderate tempos and slower swing speeds.' },

  /* ================================= ACCRA ============================== */
  { id:'accra-tz5', mfr:'Accra', series:'Tour Z', model:'Accra TZ5', gen:'Tour Z', year:2021,
    weights:[50,60,70], flexes:['R','S','X','TX'], price:475,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:5, stability:4,
    tags:['Mid launch','Mid spin','Premium smooth'],
    bestFor:'Feel-focused players wanting boutique smoothness with stability.',
    blurb:'A boutique mid/mid profile renowned for its smooth, connected feel and surprising stability — a fitter favorite.' },
  { id:'accra-tz6', mfr:'Accra', series:'Tour Z', model:'Accra TZ6', gen:'Tour Z', year:2021,
    weights:[60,70,80], flexes:['S','X','TX'], price:475,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:3, balance:2, feel:4, stability:5,
    tags:['Low-mid launch','Low spin','Firm & smooth'],
    bestFor:'Faster players wanting a firmer Accra with low spin.',
    blurb:'The firmer, lower-launching Tour Z. Keeps the boutique smoothness but adds stability and takes spin off for stronger swings.' },

  /* ================================== KBS =============================== */
  { id:'kbs-td', mfr:'KBS', series:'TD', model:'KBS TD', gen:'Tour Driven', year:2022,
    weights:[50,60,70,80], flexes:['R','S','X'], price:225,
    launch:3, spin:2, torque:3.4, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Low spin','Tunable'],
    bestFor:'Players wanting a versatile mid-launch, low-spin profile with KBS feel.',
    blurb:'A lighter, stiffer graphite driver shaft with the signature KBS feel — mid to mid-high launch with low spin and category tuning across weights.' },

  /* ================================ LA GOLF ============================= */
  { id:'lagolf-trono', mfr:'LA Golf', series:'Trono', model:'LA Golf Trono', gen:'Trono', year:2023,
    weights:[60,70,80], flexes:['S','X','TX'], price:550,
    launch:2, spin:2, torque:3.0, tip:4, mid:5, butt:3, balance:2, feel:3, stability:5,
    tags:['Low-mid launch','Low spin','Stiff mid'],
    bestFor:'Strong players wanting a stable, mid-stiff, penetrating flight.',
    blurb:'Developed with Bryson DeChambeau on LA Golf\'s 16-sided mandrel. The mid section is markedly stiffer than butt and tip, minimizing twist for a powerful, penetrating low-mid launch.' },
  { id:'lagolf-a-low', mfr:'LA Golf', series:'A-Series', model:'A-Series Low', gen:'A-Series', year:2024,
    weights:[60,70], flexes:['S','X'], price:500,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:3, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','High speed'],
    bestFor:'High swing speeds wanting low launch and low spin.',
    blurb:'The low-launch profile of LA Golf\'s simplified fitting system. Built for high swing speeds that need to take launch and spin down.' },
  { id:'lagolf-a-mid', mfr:'LA Golf', series:'A-Series', model:'A-Series Mid', gen:'A-Series', year:2024,
    weights:[50,60,70], flexes:['R','S','X'], price:500,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','Above-average speed'],
    bestFor:'Above-average swing speeds wanting a neutral, all-carbon profile.',
    blurb:'The neutral profile in LA Golf\'s A-Series. A smooth mid/mid all-carbon build for players with above-average swing speed.' },
  { id:'lagolf-a-high', mfr:'LA Golf', series:'A-Series', model:'A-Series High', gen:'A-Series', year:2024,
    weights:[40,50,60], flexes:['R','S'], price:500,
    launch:4, spin:3, torque:3.6, tip:2, mid:3, butt:3, balance:4, feel:4, stability:3,
    tags:['High launch','Mid spin','Lower speed'],
    bestFor:'Lower swing speeds wanting easy launch and carry.',
    blurb:'The high-launch A-Series. A softer, more active tip helps lower swing speeds get the ball up with all-carbon stability.' },

  /* ================================= OBAN =============================== */
  { id:'oban-kiyoshi-black', mfr:'Oban', series:'Kiyoshi', model:'Oban Kiyoshi Black', gen:'Kiyoshi', year:2019,
    weights:[50,60,70], flexes:['R','S','X'], price:425,
    launch:3, spin:3, torque:3.4, tip:3, mid:3, butt:3, balance:3, feel:5, stability:3,
    tags:['Mid launch','Mid spin','Japanese smooth'],
    bestFor:'Players who chase pure, smooth Japanese feel in a mid profile.',
    blurb:'A handcrafted Japanese profile prized for its silky, smooth load and balanced mid-launch flight.' },
  { id:'oban-revenge', mfr:'Oban', series:'Revenge', model:'Oban Revenge', gen:'Revenge', year:2023,
    weights:[50,60,70], flexes:['S','X'], price:425,
    launch:3, spin:3, torque:3.3, tip:3, mid:4, butt:3, balance:3, feel:5, stability:4,
    tags:['Mid launch','Mid spin','Stable & smooth'],
    bestFor:'Players wanting a firmer-mid Oban with added stability.',
    blurb:'A firmer-mid Oban that pairs the brand\'s smooth feel with extra stability for a controlled, repeatable mid flight.' },

  /* =============================== AUTOFLEX ============================= */
  { id:'autoflex-sf505', mfr:'Autoflex', series:'SF', model:'Autoflex SF505', gen:'SF', year:2021,
    weights:[40,50], flexes:['405','505','505x','505xx'], price:700,
    launch:5, spin:4, torque:4.5, tip:1, mid:2, butt:1, balance:5, feel:5, stability:1,
    tags:['Ultralight','Very high launch','Whippy'],
    bestFor:'Players chasing speed from an ultralight, ultra-active profile.',
    blurb:'The polarizing ultralight. A very active, whippy profile built to add clubhead speed — feel is everything and it is not for everyone.' },
];

/* ---- axes used by the radar visualization ---- */
const RADAR_AXES = [
  { key:'launch',    label:'Launch' },
  { key:'spin',      label:'Spin' },
  { key:'tip',       label:'Tip' },
  { key:'stability', label:'Stability' },
  { key:'feel',      label:'Smooth' },
  { key:'balance',   label:'Balance' },
];

/* ---- feature weights for the similarity engine ---- */
const FEATURE_WEIGHTS = {
  launch:1.0, spin:1.0, tip:1.0, mid:0.6, butt:0.6,
  balance:0.8, feel:0.7, stability:1.0,
};

/* ============================================================================
   REAL PRODUCT PHOTOS (hotlinked, shown on hover)
   Sourced from manufacturer / retailer CDNs (grips4less Shopify, truetemper).
   Add a line here to give any shaft a photo — the UI falls back to a branded
   colour swatch when an id is missing or a URL fails to load.
   ========================================================================== */
const SHAFT_IMAGES = {
  /* Fujikura — grips4less Shopify CDN */
  'fuji-ventus-blue':     'https://cdn.shopify.com/s/files/1/0095/7552/files/ventus-2024-blue_55b49156-1099-48c5-9228-29abb503d175.jpg?v=1753480081',
  'fuji-ventus-black':    'https://cdn.shopify.com/s/files/1/0095/7552/files/Ventus_Black_5-X_diag.jpg?v=1753479787',
  'fuji-ventus-red':      'https://cdn.shopify.com/s/files/1/0095/7552/files/Fujikura_Ventus_Red_5-S-diag.jpg?v=1753480051',
  'fuji-ventus-tr-blue':  'https://cdn.shopify.com/s/files/1/0095/7552/files/2026-ventus-tr-blue-velocore.jpg?v=1775978992',
  'fuji-speeder-nx-blue': 'https://cdn.shopify.com/s/files/1/0095/7552/files/SpeederNX_blue-front-1700.jpg?v=1753480316',
  'fuji-speeder-nx-violet':'https://cdn.shopify.com/s/files/1/0095/7552/files/speeder-nx-violet-1700-zoom.jpg?v=1753480018',
  /* Mitsubishi — official mitsubishigolf.com store */
  'mitsu-diamana-wb':     'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Diamana-WD-v1.3.png?v=1705273403',
  'mitsu-diamana-rb':     'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Diamana-RB-v1.1.png?v=1735764707',
  'mitsu-diamana-bb':     'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Diamana-BB-v1.1.png?v=1705277399',
  'mitsu-tensei-1k-white':'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-TENSEI-1K-White-2026-v1.1.png?v=1778645543',
  'mitsu-tensei-1k-blue': 'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-TENSEI-1K-Blue-2026-v1.1.png?v=1778645775',
  'mitsu-kaili-white':    'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Kaili-DW-White-CB-v1.1.png?v=1778817921',
  'mitsu-kaili-red':      'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Kaili-DW-Red-CB-v1.2.png?v=1778817877',
  /* Graphite Design — fairwayjockey Shopify CDN */
  'gd-ad-di':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/DIBlack.jpg?v=1738269976',
  'gd-ad-vf':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/Graphite-Design-Tour-AD-VF.png?v=1701282771',
  'gd-ad-iz':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/Graphite_Design_Tour_AD_IZ.jpg?v=1634336231',
  'gd-ad-ub':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/Graphite-Design-Tour-AD-UB-Shaft.png?v=1634335102',
  'gd-ad-cq':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/Graphite-Design-Tour-AD-CQ.png?v=1667246380',
  'gd-ad-xc':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/Graphite_Design_Tour_AD_XC.jpg?v=1634592636',
  /* Project X — official truetemper.com store */
  'px-denali-black':      'https://www.truetemper.com/cdn/shop/files/denali_frost_black_web.png?v=1773076138&width=1206',
  'px-denali-blue':       'https://www.truetemper.com/cdn/shop/files/denali_frost_blue_web_3c3626ce-1ab6-402f-bed7-c8cc85229b35.png?v=1773076255&width=1206',
  'px-denali-red':        'https://www.truetemper.com/cdn/shop/files/denali_frost_web.png?v=1773076133&width=1206',
  'px-hzrdus-black-g5':   'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/HZRDUS_G5Black_45.png?v=1773766997',
  /* Aldila — grips4less */
  'aldila-quaranta':      'https://cdn.shopify.com/s/files/1/0095/7552/products/aldila-quaranta-gold-600_1597d8a1-691d-4c95-b5a1-0817699e763d.jpg',
  /* UST Mamiya — fairwayjockey */
  'ust-linq-blue':        'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/LIN-QPCBlueCustom.png?v=1767815413',
  /* Accra — fairwayjockey (Tour Z family) */
  'accra-tz5':            'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/2_d6c3d512-56b6-4f97-9be0-4e7597c09002.png?v=1771619242',
  'accra-tz6':            'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/2_d6c3d512-56b6-4f97-9be0-4e7597c09002.png?v=1771619242',
  /* LA Golf — fairwayjockey */
  'lagolf-trono':         'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/LAGP-Bryson-R1.png?v=1648492374',
  'lagolf-a-low':         'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/LA-Golf-LA-Series_40fc98ff-fcfb-4d89-be20-b3656e08ab40.png?v=1648708343',
  'lagolf-a-mid':         'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/LA-Golf-LA-Series_40fc98ff-fcfb-4d89-be20-b3656e08ab40.png?v=1648708343',
  'lagolf-a-high':        'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/LA-Golf-LA-Series_40fc98ff-fcfb-4d89-be20-b3656e08ab40.png?v=1648708343',
  /* Autoflex — grips4less */
  'autoflex-sf505':       'https://cdn.shopify.com/s/files/1/0095/7552/files/autoflex-original-black.jpg?v=1761174225',
};

/* ---- representative paint-scheme colour for every shaft (fallback swatch + UI dot) ---- */
const SHAFT_COLORS = {
  'fuji-ventus-blue':'#2f6fb0','fuji-ventus-black':'#16181b','fuji-ventus-red':'#b22f2a',
  'fuji-ventus-white':'#dfe2e6','fuji-ventus-tr-blue':'#1d3f78','fuji-ventus-tr-black':'#0f1113',
  'fuji-speeder-nx-blue':'#2b6bce','fuji-speeder-nx-green':'#2e8b57','fuji-speeder-nx-violet':'#6b4fa0',
  'mitsu-diamana-wb':'#d9dde2','mitsu-diamana-rb':'#b83a3f','mitsu-diamana-bb':'#29487d',
  'mitsu-tensei-1k-white':'#e3e5e8','mitsu-tensei-1k-blue':'#245a9e',
  'mitsu-kaili-white':'#dfe2e6','mitsu-kaili-blue':'#2766b3','mitsu-kaili-red':'#b3322c','mitsu-vanquish-green':'#3aa05a',
  'gd-ad-vr':'#1c2f5e','gd-ad-cq':'#3b3f46','gd-ad-di':'#26282d','gd-ad-iz':'#243a6b',
  'gd-ad-xc':'#4a2f6b','gd-ad-vf':'#6b1f2a','gd-ad-ub':'#b07a2a','gd-ad-gp':'#2e7d5b',
  'px-denali-black':'#1a1c1f','px-denali-blue':'#2a5fa0','px-denali-red':'#b13030',
  'px-hzrdus-black-g5':'#161719','px-hzrdus-blue-g5':'#234e86',
  'aldila-rogue-white':'#e1e3e6','aldila-quaranta':'#c9a23a',
  'ust-elements-earth':'#6b4a2a','ust-elements-fire':'#c2502a','ust-elements-wind':'#4a8fb0',
  'ust-linq-blue':'#234e86','ust-helium':'#7fb53a',
  'accra-tz5':'#2a2d33','accra-tz6':'#1c1e22','kbs-td':'#2a2d33',
  'lagolf-trono':'#b8932f','lagolf-a-low':'#1a1c1f','lagolf-a-mid':'#3a3d44','lagolf-a-high':'#b0b3b8',
  'oban-kiyoshi-black':'#15171a','oban-revenge':'#2a2d33','autoflex-sf505':'#d65a2a',
};

/* ---- VERIFIED published specs (real manufacturer numbers) for select models ----
   Shafts not listed here display their relative profile only, marked "est." ---- */
const SHAFT_SPECS = {
  'fuji-ventus-white':{ length:'46"', weight:'49–50g', torque:'5.0°', tip:'0.335"', butt:'0.602"', launch:'High', spin:'Mid-High' },
  'fuji-ventus-blue': { length:'46"', weight:'58–94g', torque:'2.8–3.9°', tip:'0.335"', butt:'0.602"', launch:'Mid', spin:'Low-Mid' },
  'fuji-ventus-black':{ length:'46"', weight:'80–93g', torque:'2.8–3.5°', tip:'0.335"', butt:'0.602"', launch:'Low', spin:'Low' },
  'fuji-ventus-red':  { length:'46"', weight:'59–94g', torque:'2.8–3.8°', tip:'0.335"', butt:'0.602"', launch:'Mid-High', spin:'Mid' },
  'px-denali-black':  { length:'46"', weight:'66–86g', torque:'2.8–3.6°', tip:'0.335"', butt:'0.600"', launch:'Low', spin:'Low' },
  'px-denali-blue':   { length:'46"', weight:'58–78g', torque:'2.7–4.5°', tip:'0.335"', butt:'0.600"', launch:'Mid', spin:'Mid' },
  'px-denali-red':    { length:'46"', weight:'48–65g', torque:'4.9–5.4°', tip:'0.335"', butt:'0.600"', launch:'High', spin:'Mid-High' },
  'autoflex-sf505':   { length:'45"', weight:'~50g (505)', torque:'—', tip:'0.335"', butt:'0.600"', launch:'High', spin:'Mid-High', note:'Club-speed band: 95–100 mph (SF505)' },
};
