/* ============================================================================
   SHAFTOLOGY — Aftermarket Driver Shaft Database
   ----------------------------------------------------------------------------
   Lineups reflect models current as of the 2026 season (researched from
   manufacturer + retailer sources, June 2026). Profile fields are RELATIVE
   1–5 scales unless noted — directional fitting characteristics for
   comparison, NOT exact OEM lab numbers:

     launch      1 = very low ............ 5 = very high
     spin        1 = very low ............ 5 = very high
     tip         tip stiffness  1 = active/soft ... 5 = stout/boardy
     mid         mid stiffness  1 = soft .......... 5 = firm
     butt        handle stiffness 1 = soft ........ 5 = firm
     balance     1 = tip-heavy .......... 5 = counterbalanced (butt-heavy)
     feel        1 = boardy/harsh ....... 5 = smooth/buttery
     stability   1 = whippy ............. 5 = rock-solid (low torque feel)
     torque      approx degrees @ ~6S (lower = more stable)

   weights = available class weights (g). flexes = available flexes.
   ========================================================================== */

const SHAFTS = [
  /* ================================ FUJIKURA ============================== */
  { id:'fuji-ventus-blue', mfr:'Fujikura', series:'Ventus', model:'Ventus Blue', gen:'VeloCore+', year:2025,
    weights:[50,60,70,80], flexes:['R','S','X','TX'], price:375,
    launch:3, spin:2, torque:3.1, tip:4, mid:3, butt:3, balance:3, feel:3, stability:5,
    tags:['Mid launch','Low-mid spin','Stable tip'],
    bestFor:'Players wanting a stable mid-launch profile that holds up under speed.',
    blurb:'The benchmark all-rounder, now on VeloCore+. The added premium bias-core material tightens dispersion and adds ball speed while keeping the trusted stable mid flight.' },
  { id:'fuji-ventus-black', mfr:'Fujikura', series:'Ventus', model:'Ventus Black', gen:'VeloCore+', year:2025,
    weights:[60,70,80], flexes:['S','X','TX'], price:375,
    launch:2, spin:1, torque:2.9, tip:5, mid:4, butt:4, balance:2, feel:2, stability:5,
    tags:['Low launch','Low spin','Stout tip'],
    bestFor:'High-speed, aggressive transitions chasing the lowest spin.',
    blurb:'The stoutest of the family and the shaft trusted by every 2025 men\'s major champion. A genuinely firm tip and handle for hard loaders who want to flatten the window.' },
  { id:'fuji-ventus-red', mfr:'Fujikura', series:'Ventus', model:'Ventus Red', gen:'VeloCore+', year:2025,
    weights:[50,60,70], flexes:['R','S','X'], price:375,
    launch:4, spin:3, torque:3.6, tip:3, mid:3, butt:2, balance:4, feel:4, stability:4,
    tags:['Mid-high launch','Counterbalanced','Active tip'],
    bestFor:'Smoother tempos who want help launching it with a counterbalanced feel.',
    blurb:'The launch-friendly sibling. A softer handle and counterbalanced build add ramp to the flight while VeloCore+ keeps the tip respectable.' },
  { id:'fuji-ventus-white', mfr:'Fujikura', series:'Ventus', model:'Ventus White', gen:'VeloCore+', year:2025,
    weights:[40,50], flexes:['R2','R','S'], price:375,
    launch:4, spin:3, torque:4.0, tip:3, mid:3, butt:3, balance:3, feel:4, stability:3,
    tags:['Lightweight','High launch','Mid-high spin'],
    bestFor:'Speed-seekers who want easy launch in a sub-50g Ventus build.',
    blurb:'The newest profile of 2025 — VeloCore+ in an ultralight (~50g) package. Per Fujikura\'s own spec chart it flies HIGH with mid-high spin, rounding out the line below the heavier Blue/Black/Red.' },
  { id:'fuji-ventus-tr-blue', mfr:'Fujikura', series:'Ventus', model:'Ventus TR Blue', gen:'VeloCore+', year:2026,
    weights:[50,60,70], flexes:['S','X','TX'], price:400,
    launch:3, spin:2, torque:3.0, tip:4, mid:4, butt:3, balance:3, feel:3, stability:5,
    tags:['Mid launch','Lower spin','Tour Spec'],
    bestFor:'Ventus Blue lovers who want firmer mid-section and tighter spin.',
    blurb:'The 2026 Tour Spec evolution. VeloCore+ paired with Spread Tow fabric reinforces the mid-section for greater stability, a more refined feel, and more speed through impact.' },
  { id:'fuji-ventus-tr-black', mfr:'Fujikura', series:'Ventus', model:'Ventus TR Black', gen:'VeloCore+', year:2026,
    weights:[60,70,80], flexes:['X','TX'], price:400,
    launch:1, spin:1, torque:2.8, tip:5, mid:5, butt:4, balance:2, feel:2, stability:5,
    tags:['Very low launch','Very low spin','Boardy'],
    bestFor:'Elite speed delivering huge load that needs the flattest flight.',
    blurb:'The firmest shaft Fujikura builds for 2026. VeloCore+ plus Spread Tow in the most stout TR profile — minimal launch, minimal spin, maximum stability.' },
  { id:'fuji-speeder-nx-blue', mfr:'Fujikura', series:'Speeder', model:'Speeder NX Blue', gen:'VTC', year:2024,
    weights:[50,60,70], flexes:['R','S','X'], price:350,
    launch:3, spin:3, torque:3.5, tip:3, mid:3, butt:3, balance:3, feel:4, stability:3,
    tags:['Mid launch','Mid spin','Smooth'],
    bestFor:'Tempos that want classic Speeder rhythm with a mid profile.',
    blurb:'Variable Torque Core tunes stiffness along the shaft for the signature smooth, rhythmic Speeder load in a balanced mid-launch package.' },
  { id:'fuji-speeder-nx-green', mfr:'Fujikura', series:'Speeder', model:'Speeder NX Green', gen:'VTC', year:2024,
    weights:[50,60,70], flexes:['R','S','X','TX'], price:350,
    launch:3, spin:2, torque:3.3, tip:4, mid:3, butt:3, balance:3, feel:3, stability:4,
    tags:['Mid launch','Low spin','Stable'],
    bestFor:'Players wanting low spin without going fully stout.',
    blurb:'A spin-killer that still feels lively. Variable Torque Core keeps it stable through the strike with a smoother load than the boards.' },
  { id:'fuji-speeder-nx-violet', mfr:'Fujikura', series:'Speeder', model:'Speeder NX Violet', gen:'VTC · DHX', year:2026,
    weights:[40,50,60], flexes:['R','S','X'], price:375,
    launch:3, spin:3, torque:3.6, tip:3, mid:2, butt:3, balance:4, feel:5, stability:3,
    tags:['Speed-biased','Mid launch','Smooth'],
    bestFor:'Players hunting clubhead speed from a smooth, active profile.',
    blurb:'New for 2026. Built on the NX Blue profile with breakthrough DHX technology to maximize clubhead speed — a lively, smooth-loading shaft for distance.' },
  { id:'fuji-speeder-nx-gold', mfr:'Fujikura', series:'Speeder', model:'Speeder NX Gold', gen:'VTC', year:2025,
    weights:[40,50,60,70], flexes:['R2','R','SR','S','X'], price:375,
    launch:3, spin:2, torque:3.3, tip:4, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Low-mid spin','Smooth & stable'],
    bestFor:'Players wanting a smooth, stable mid profile with low-mid spin.',
    blurb:'The premium NX. A Variable Torque Core delivers a smooth, stable load with mid launch and low-mid spin — a refined all-rounder for a wide range of speeds.' },

  /* =============================== MITSUBISHI ============================= */
  { id:'mitsu-diamana-wb', mfr:'Mitsubishi', series:'Diamana', model:'Diamana WB', gen:'6th Gen', year:2025,
    weights:[50,60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:2, torque:3.1, tip:4, mid:5, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Firm mid'],
    bestFor:'Strong players wanting the firm-mid white-board flight.',
    blurb:'The firm-mid profile of the 6th-generation Diamana. Xlink Tech resin drives carbon volume up for better feel while the stiff mid flattens the window for fast swings.' },
  { id:'mitsu-diamana-rb', mfr:'Mitsubishi', series:'Diamana', model:'Diamana RB', gen:'6th Gen', year:2025,
    weights:[50,60,70], flexes:['R','S','X'], price:400,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:4, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','Energy butt'],
    bestFor:'The neutral, do-everything 6th-gen Diamana fitting.',
    blurb:'The neutral-mid profile. 80-Ton Dialead pitch fiber in the butt drives maximum energy transfer, giving a smooth but efficient mid/mid flight.' },
  { id:'mitsu-diamana-bb', mfr:'Mitsubishi', series:'Diamana', model:'Diamana BB', gen:'6th Gen', year:2025,
    weights:[40,50,60,70], flexes:['R','S','X'], price:400,
    launch:4, spin:3, torque:3.6, tip:3, mid:2, butt:3, balance:3, feel:5, stability:3,
    tags:['Mid-high launch','Mid spin','Soft mid'],
    bestFor:'Smoother tempos wanting easy launch and signature Diamana feel.',
    blurb:'The soft-mid, blue-board-style member of the 6th generation. An easy, high-launching load defined by that silky, connected Diamana feel.' },
  { id:'mitsu-tensei-1k-white', mfr:'Mitsubishi', series:'Tensei', model:'Tensei 1K Pro White', gen:'1K', year:2023,
    weights:[60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:2, torque:3.1, tip:5, mid:4, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Premium stout'],
    bestFor:'High-speed players wanting a premium, very stable low-launch build.',
    blurb:'1K carbon weave wraps a genuinely stout profile — firm tip to handle with exceptional hoop strength and stability for the strongest swings.' },
  { id:'mitsu-tensei-1k-blue', mfr:'Mitsubishi', series:'Tensei', model:'Tensei 1K Pro Blue', gen:'1K', year:2023,
    weights:[50,60,70], flexes:['R','S','X'], price:400,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','All-around'],
    bestFor:'A smooth, neutral mid profile with premium 1K feel.',
    blurb:'The neutral 1K profile. A smooth-loading mid/mid build with the dampened, premium feel of the 1K carbon handle.' },
  { id:'mitsu-tensei-1k-red', mfr:'Mitsubishi', series:'Tensei', model:'Tensei 1K Pro Red', gen:'1K', year:2024,
    weights:[50,60,70], flexes:['R','S','X'], price:400,
    launch:4, spin:3, torque:3.5, tip:2, mid:3, butt:2, balance:4, feel:4, stability:3,
    tags:['High launch','Mid spin','Active tip'],
    bestFor:'Moderate tempos wanting easy launch and a smooth, active feel.',
    blurb:'The high-launch 1K Pro. An active tip and counterbalanced build lift the flight, wrapped in the premium 1K carbon handle for a dampened, smooth feel.' },
  { id:'mitsu-kaili-white', mfr:'Mitsubishi', series:"Kai'li", model:"Kai'li White", gen:"Kai'li", year:2023,
    weights:[60,70,80], flexes:['S','X','TX'], price:375,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:3, balance:3, feel:3, stability:5,
    tags:['Low launch','Low spin','Stable'],
    bestFor:'Players chasing a stable, low-launch tour profile.',
    blurb:'The low-launch, low-spin member of the Kai\'li line — firm and quiet through impact for stronger players.' },
  { id:'mitsu-kaili-blue', mfr:'Mitsubishi', series:"Kai'li", model:"Kai'li Blue", gen:"Kai'li", year:2023,
    weights:[50,60,70], flexes:['R','S','X'], price:375,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:3,
    tags:['Mid launch','Mid spin','Smooth'],
    bestFor:'A neutral, smooth mid profile for a wide range of speeds.',
    blurb:'The balanced, smooth-loading mid/mid option — the versatile middle child of the Kai\'li family.' },
  { id:'mitsu-kaili-red', mfr:'Mitsubishi', series:"Kai'li", model:"Kai'li Red", gen:"Kai'li", year:2024,
    weights:[40,50,60], flexes:['R','S','X'], price:375,
    launch:4, spin:3, torque:3.6, tip:2, mid:3, butt:3, balance:4, feel:4, stability:3,
    tags:['High launch','Mid spin','Counterbalanced'],
    bestFor:'Moderate tempos wanting added height and carry.',
    blurb:'The high-launch Kai\'li. A softer, more active tip and counterbalanced build add easy height for moderate swing speeds.' },
  { id:'mitsu-vanquish-green', mfr:'Mitsubishi', series:'Vanquish', model:'Vanquish Green', gen:'Vanquish', year:2024,
    weights:[40,50], flexes:['R','S'], price:300,
    launch:5, spin:4, torque:4.2, tip:2, mid:2, butt:2, balance:4, feel:5, stability:2,
    tags:['Ultralight','High launch','Smooth'],
    bestFor:'Moderate and slower swing speeds needing speed and height.',
    blurb:'An ultralight, high-launch profile built to add clubhead speed and carry for moderate tempos.' },

  /* ============================ GRAPHITE DESIGN ========================== */
  { id:'gd-ad-vr', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD VR', gen:'VR', year:2024,
    weights:[40,50,60,70,80], flexes:['R2','R1','SR','S','X'], price:450,
    launch:4, spin:2, torque:3.3, tip:4, mid:4, butt:4, balance:3, feel:4, stability:4,
    tags:['Mid-high launch','Low spin','Firm overall'],
    bestFor:'Players wanting mid-high launch with genuinely low spin.',
    blurb:'"Vanquish all Rivals." Firm-to-stiff from the handle through a medium/firm center to a firm tip — a rare combination of mid-high launch with low spin.' },
  { id:'gd-ad-cq', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD CQ', gen:'CQ', year:2024,
    weights:[40,50,60,70], flexes:['R','SR','S','X'], price:450,
    launch:4, spin:3, torque:3.4, tip:3, mid:3, butt:3, balance:3, feel:5, stability:4,
    tags:['Mid-high launch','Controlled spin','Smooth'],
    bestFor:'Players wanting easy launch with stability and a smooth feel.',
    blurb:'Built with Graphite Design\'s Material Stiffness Integration process and aerospace-grade carbon for torsional resistance — mid-to-high launch with controlled, repeatable spin.' },
  { id:'gd-ad-fi', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD FI', gen:'FI', year:2024,
    weights:[40,50,60,70,80], flexes:['R2','R1','SR','S','X','TX'], price:450,
    launch:3, spin:2, torque:3.2, tip:4, mid:4, butt:4, balance:3, feel:4, stability:4,
    tags:['Mid launch','Low spin','Firm throughout'],
    bestFor:'Players wanting a firm, stable mid-launch profile with low spin.',
    blurb:'A firm-throughout profile — Firm+ handle and mid-section with a stiff tip — for a stable mid-launch flight with low-to-low/mid spin. Graphite Design\'s "Flight Intelligence" build pairs AD Shield with Tornado Tip tech.' },
  { id:'gd-ad-gc', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD GC', gen:'GC', year:2024,
    weights:[40,50,60,70,80], flexes:['R2','R1','SR','S','X','TX'], price:450,
    launch:3, spin:2, torque:3.1, tip:4, mid:4, butt:5, balance:3, feel:4, stability:5,
    tags:['Mid launch','Low-mid spin','Stiff handle'],
    bestFor:'Players wanting a firm, stable mid-launch profile with a stiff handle.',
    blurb:'A stiff butt, firm center and firm+ tip give the GC mid launch with low-to-mid spin and a notably stable, controlled feel through the strike.' },
  { id:'gd-ad-hd', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD HD', gen:'HD', year:2023,
    weights:[40,50,60,70,80], flexes:['R2','R1','SR','S','X','TX'], price:450,
    launch:3, spin:2, torque:3.0, tip:4, mid:4, butt:4, balance:3, feel:4, stability:5,
    tags:['Mid launch','Low spin','Firm throughout'],
    bestFor:'Players chasing accuracy and distance from a firm, low-spin mid-launch build.',
    blurb:'TORAYCA M40X and T1100G carbon combine for a firm butt, firm center and firm+ tip — mid launch with low to low/mid spin, tuned for accuracy and distance.' },
  { id:'gd-ad-di', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD DI', gen:'DI', year:2019,
    weights:[50,60,70,80], flexes:['R','S','X','TX'], price:400,
    launch:3, spin:3, torque:3.3, tip:4, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','Firm tip'],
    bestFor:'The timeless tour profile that flatters almost everyone.',
    blurb:'Arguably the most successful aftermarket profile ever. A firm tip with a smooth overall load — mid/mid with rock-steady dispersion.' },
  { id:'gd-ad-iz', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD IZ', gen:'IZ', year:2018,
    weights:[50,60,70,80], flexes:['R','S','X','TX'], price:400,
    launch:3, spin:2, torque:3.2, tip:4, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Low-mid spin','Stable impact'],
    bestFor:'DI fans who want a touch lower spin and a firmer mid-strike.',
    blurb:'A more stable-through-impact DI variant. Holds the face square at speed with slightly tighter spin numbers.' },
  { id:'gd-ad-xc', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD XC', gen:'XC', year:2020,
    weights:[50,60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:4, balance:2, feel:3, stability:5,
    tags:['Low-mid launch','Low spin','Firm tip & handle'],
    bestFor:'Strong transitions wanting firm tip plus a firm handle.',
    blurb:'Firm in both the tip and the butt — a double-stiff profile that rewards aggressive, fast players with low spin and tight dispersion.' },
  { id:'gd-ad-vf', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD VF', gen:'VF', year:2021,
    weights:[50,60,70,80], flexes:['S','X','TX'], price:400,
    launch:2, spin:1, torque:3.0, tip:4, mid:5, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Very low spin','Stiff mid'],
    bestFor:'Players who deliver a lot of load and need a firm mid-section.',
    blurb:'A uniquely firm mid-section defines the VF. It resists ballooning for hard swingers and produces a flat, low-spin window.' },
  { id:'gd-ad-ub', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD UB', gen:'UB', year:2022,
    weights:[40,50,60,70], flexes:['R','S','X'], price:400,
    launch:4, spin:3, torque:3.5, tip:3, mid:2, butt:3, balance:3, feel:5, stability:3,
    tags:['Mid-high launch','Mid spin','Smooth mid'],
    bestFor:'Smoother tempos wanting easy launch and a buttery mid.',
    blurb:'A softer mid-section gives the UB an easy, high-launching load with the signature Graphite Design smoothness.' },
  { id:'gd-ad-gp', mfr:'Graphite Design', series:'Tour AD', model:'Tour AD GP', gen:'GP', year:2017,
    weights:[40,50,60,70], flexes:['R','S','X'], price:400,
    launch:5, spin:4, torque:3.7, tip:2, mid:3, butt:2, balance:4, feel:5, stability:3,
    tags:['High launch','High spin','Easy load'],
    bestFor:'Moderate speeds needing maximum carry and a soft tip.',
    blurb:'The launch monster of the line. A softer tip and counterbalanced build add height and carry for moderate swing speeds.' },

  /* =============================== PROJECT X ============================= */
  { id:'px-titan-black', mfr:'Project X', series:'TITAN', model:'TITAN Black', gen:'TITAN', year:2026,
    weights:[60,70,80], flexes:['5.5','6.0','6.5','TX'], price:425,
    launch:2, spin:1, torque:3.2, tip:5, mid:4, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Rock-solid tip'],
    bestFor:'Aggressive, high-speed swings wanting the most penetrating flight.',
    blurb:'Project X\'s new flagship. A stout, low-torque profile built to deliver the penetrating low-launch, low-spin trajectory elite players demand, with rock-solid tip stability.' },
  { id:'px-titan-yellow', mfr:'Project X', series:'TITAN', model:'TITAN Yellow', gen:'TITAN', year:2026,
    weights:[60,70,80], flexes:['5.5','6.0','6.5','TX'], price:425,
    launch:2, spin:2, torque:3.2, tip:4, mid:3, butt:3, balance:4, feel:3, stability:5,
    tags:['Low launch','Low spin','Counterbalanced'],
    bestFor:'Fast tempos wanting low spin from a lighter-feeling, counterbalanced build.',
    blurb:'The counterbalanced TITAN. Keeps the low-launch, low-spin penetrating flight with rock-solid tip stability, in a build engineered not to feel heavy for aggressive acceleration.' },
  { id:'px-denali-black', mfr:'Project X', series:'Denali', model:'Denali Frost Black', gen:'Frost G2', year:2025,
    weights:[60,70,80], flexes:['6.0','6.5','TX'], price:400,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:3, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Stable'],
    bestFor:'Fast players wanting a modern, refined low-launch build.',
    blurb:'The low-launch Frost. Second-gen Denali with Focused Rotational Stability tech for tighter dispersion and a smooth, controlled, quiet flight.' },
  { id:'px-denali-blue', mfr:'Project X', series:'Denali', model:'Denali Frost Blue', gen:'Frost G2', year:2025,
    weights:[50,60,70], flexes:['6.0','6.5','TX'], price:400,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','Smooth'],
    bestFor:'The neutral, do-everything Denali fitting.',
    blurb:'The mid/mid Frost. Focused Rotational Stability tech adds off-center stability to a smooth, neutral profile that suits the widest range of players.' },
  { id:'px-denali-red', mfr:'Project X', series:'Denali', model:'Denali Frost Red', gen:'Frost G2', year:2025,
    weights:[40,50,60], flexes:['5.0','5.5','6.0'], price:400,
    launch:4, spin:4, torque:3.8, tip:2, mid:3, butt:2, balance:4, feel:4, stability:3,
    tags:['High launch','Higher spin','Counterbalanced'],
    bestFor:'Moderate speeds prioritizing carry and an easy load.',
    blurb:'The launch-and-carry Frost. A soft tip and counterbalanced build make it one of the easiest premium shafts to elevate.' },
  { id:'px-hzrdus-t1100', mfr:'Project X', series:'HZRDUS', model:'HZRDUS T1100 Handcrafted', gen:'T1100', year:2025,
    weights:[60,70], flexes:['6.0','6.5'], price:500,
    launch:2, spin:1, torque:2.4, tip:5, mid:4, butt:4, balance:2, feel:3, stability:5,
    tags:['Very low launch','Very low spin','Ultra-stable'],
    bestFor:'The fastest swingers chasing ultimate launch and spin control.',
    blurb:'Project X\'s most stable wood shaft ever. Handcrafted 4D-Optimized Carbon with a strategically angled weave drops torque to ~2.3° for ultimate launch and spin control at elite speed.' },
  { id:'px-hzrdus-black-g5', mfr:'Project X', series:'HZRDUS', model:'HZRDUS G5 Black', gen:'G5', year:2024,
    weights:[60,70,80], flexes:['5.5','6.0','6.5','TX'], price:300,
    launch:2, spin:1, torque:3.2, tip:4, mid:4, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Tour stable'],
    bestFor:'Faster tempos wanting low spin and tight dispersion.',
    blurb:'A 4D-Optimized Carbon weave in the midsection adds torsional resistance and energy transfer — low launch, low spin, and tour-level stability for tight dispersion.' },
  { id:'px-hzrdus-g5-yellow', mfr:'Project X', series:'HZRDUS', model:'HZRDUS G5 Yellow', gen:'G5', year:2024,
    weights:[60,70,80], flexes:['5.5','6.0','6.5','TX'], price:350,
    launch:2, spin:1, torque:3.0, tip:5, mid:3, butt:4, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Stiff butt & tip'],
    bestFor:'Aggressive swingers wanting double-stiff ends with a responsive mid.',
    blurb:'A stiff butt and tip section keep launch and spin down while a more responsive midsection adds feel — the handcrafted, lower-spinning Gen 5 for aggressive swingers.' },
  { id:'px-cypher-20', mfr:'Project X', series:'Cypher', model:'Cypher 2.0', gen:'2.0', year:2024,
    weights:[40,50,60], flexes:['4.0','5.0','5.5','6.0'], price:80,
    launch:4, spin:3, torque:5.0, tip:2, mid:2, butt:2, balance:3, feel:4, stability:2,
    tags:['Ultralight','High launch','Distance'],
    bestFor:'Moderate-to-fast tempos chasing speed and height from an ultralight build.',
    blurb:'An ultralightweight, higher-launch shaft built to maximize distance through added swing speed — a 5% lighter weave than its predecessor for moderate-to-aggressive tempos.' },

  /* ================================= ALDILA ============================== */
  { id:'aldila-rogue-inf', mfr:'Aldila', series:'Rogue', model:'Rogue ∞', gen:'Infinity', year:2024,
    weights:[50,60,70,80], flexes:['TR','TS','TX'], price:350,
    launch:3, spin:2, torque:3.6, tip:3, mid:3, butt:4, balance:5, feel:5, stability:4,
    tags:['Mid launch','Mid-low spin','Heavily counterbalanced'],
    bestFor:'Players wanting a smooth, heavily counterbalanced build with tight dispersion.',
    blurb:'Dual Torque Core pairs 80-Ton and 46-Ton pitch fiber for low torque with a smooth feel. A heavily counterbalanced (.640"+ butt) mid-launch, mid-low-spin profile from a family with 70+ tour wins.' },
  { id:'aldila-rogue-silver', mfr:'Aldila', series:'Rogue', model:'Rogue Silver 110 2nd Gen', gen:'Silver 110', year:2024,
    weights:[60,70], flexes:['R','S','X'], price:275,
    launch:2, spin:2, torque:3.2, tip:5, mid:4, butt:3, balance:2, feel:3, stability:5,
    tags:['Low-mid launch','Low spin','Stiff tip'],
    bestFor:'Stronger players wanting a stiff-tip, low-spin profile.',
    blurb:'A stiff-tip profile with a mid/high kick point and NexGen Micro Laminate Technology — mid/low launch and mid/low spin for controlled, penetrating flight.' },
  { id:'aldila-quaranta-gold', mfr:'Aldila', series:'Quaranta', model:'Quaranta Gold', gen:'Quaranta', year:2025,
    weights:[40,50], flexes:['R2','R','S'], price:225,
    launch:4, spin:3, torque:6.0, tip:2, mid:2, butt:2, balance:3, feel:5, stability:2,
    tags:['Ultralight','Mid launch','Smooth'],
    bestFor:'Moderate and slower tempos chasing speed and a smooth, easy launch.',
    blurb:'Sub-40g ultralight with a low kick point and high-modulus MR70 carbon in the tip — a smooth, mid-launch profile built to add clubhead speed.' },
  { id:'aldila-quaranta-sapphire', mfr:'Aldila', series:'Quaranta', model:'Quaranta Sapphire', gen:'Quaranta', year:2025,
    weights:[40,50], flexes:['A','R','SR','S'], price:225,
    launch:3, spin:2, torque:4.8, tip:3, mid:3, butt:4, balance:3, feel:4, stability:3,
    tags:['Lightweight','Mid-low launch','Flatter flight'],
    bestFor:'Speed-seekers wanting a lighter build with a flatter, more stable flight.',
    blurb:'A sub-50g Quaranta with a responsive tip and mid-section balanced by a more stable butt — lower-launching and flatter than the Blue Series, with MR70 carbon.' },
  { id:'aldila-nv-green', mfr:'Aldila', series:'NV', model:'NV Green', gen:'NV', year:2024,
    weights:[50,60,70,80], flexes:['R','S','X'], price:200,
    launch:2, spin:2, torque:3.5, tip:4, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Low launch','Low spin','Classic'],
    bestFor:'Players wanting the classic low-launch NV Green flight.',
    blurb:'The low-launch, low-spin NV. A constant-taper design with a mid/high kick point and NexGen Micro Laminate Technology for stable, penetrating flight.' },
  { id:'aldila-ascent-ul', mfr:'Aldila', series:'Ascent', model:'Ascent Ultralight', gen:'Ascent', year:2024,
    weights:[40,50], flexes:['R3','R2','R','S'], price:175,
    launch:5, spin:4, torque:8.2, tip:1, mid:2, butt:2, balance:3, feel:5, stability:1,
    tags:['Ultralight','High launch','Easy load'],
    bestFor:'Slower and moderate swing speeds wanting maximum height and an easy load.',
    blurb:'A featherweight (41–48g) high-launch profile with a low kick point — an easy, high launch angle for a wide span of swing speeds.' },

  /* ============================== UST MAMIYA ============================= */
  { id:'ust-linq-pc-white', mfr:'UST Mamiya', series:'LIN-Q', model:'LIN-Q PowerCore White', gen:'PowerCore', year:2024,
    weights:[60,70,80], flexes:['R','S','X'], price:350,
    launch:2, spin:2, torque:3.3, tip:4, mid:4, butt:3, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','Stable'],
    bestFor:'Strong players wanting a stable, low-launch, low-spin flight.',
    blurb:'The low-launch PowerCore. Q-Ply material and ion-plated carbon deliver multi-axis stability and a penetrating, low-spinning window for faster swings.' },
  { id:'ust-linq-blue', mfr:'UST Mamiya', series:'LIN-Q', model:'LIN-Q PowerCore Blue', gen:'PowerCore', year:2024,
    weights:[50,60,70], flexes:['R','S','X'], price:350,
    launch:3, spin:2, torque:3.5, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Low spin','All-around'],
    bestFor:'The neutral, broadly fittable PowerCore profile.',
    blurb:'The mid-launch PowerCore. A distinct mandrel and layup with a nano resin system give it launch consistency and stability in a smooth, mid/low-spin build.' },
  { id:'ust-linq-pc-red', mfr:'UST Mamiya', series:'LIN-Q', model:'LIN-Q PowerCore Red', gen:'PowerCore', year:2024,
    weights:[50,60,70], flexes:['R','S','X'], price:350,
    launch:4, spin:2, torque:3.6, tip:2, mid:3, butt:2, balance:4, feel:4, stability:3,
    tags:['High launch','Low spin','Counterbalanced'],
    bestFor:'Moderate tempos wanting easy launch with low spin.',
    blurb:'The high-launch PowerCore. A softer, more active tip and counterbalanced build lift the flight while Q-Ply keeps spin down.' },
  { id:'ust-helium', mfr:'UST Mamiya', series:'Helium', model:'Helium NCT', gen:'NCT', year:2024,
    weights:[40,50], flexes:['A','R','S'], price:175,
    launch:5, spin:4, torque:6.1, tip:2, mid:2, butt:2, balance:4, feel:5, stability:2,
    tags:['Ultralight','High launch','Counterbalanced'],
    bestFor:'Moderate and slower swing speeds needing speed and height.',
    blurb:'An ultralight (44–56g), counterbalanced high-launch profile with low-resin carbon — built to add clubhead speed and carry for moderate tempos.' },
  { id:'ust-proforce-v2', mfr:'UST Mamiya', series:'ProForce', model:'ProForce V2', gen:'V2', year:2023,
    weights:[60,70,80], flexes:['R','S','X'], price:150,
    launch:3, spin:2, torque:3.5, tip:4, mid:3, butt:3, balance:2, feel:3, stability:4,
    tags:['Mid launch','Low spin','Penetrating'],
    bestFor:'Players wanting a penetrating, low-torque classic at a friendly price.',
    blurb:'The classic ProForce V2, updated. Aerospace-grade, low-torque construction delivers a penetrating mid-launch flight with lateral stability and ball speed.' },

  /* ================================= ACCRA ============================== */
  { id:'accra-tour-z-red', mfr:'Accra', series:'Tour Z', model:'Accra Tour Z Red', gen:'Tour Z', year:2025,
    weights:[60,70,80], flexes:['M3','M4','M5'], price:475,
    launch:2, spin:2, torque:3.5, tip:4, mid:4, butt:4, balance:3, feel:4, stability:5,
    tags:['Low launch','Low spin','Aggressive'],
    bestFor:'Aggressive, high-speed swings chasing the lowest launch and spin.',
    blurb:'The low-launch, low-spin Tour Z for hard loaders. Offered in M3–M5 with a stout, stable profile that flattens the window for aggressive transitions while keeping Accra\'s signature smoothness.' },
  { id:'accra-tour-z-green', mfr:'Accra', series:'Tour Z', model:'Accra Tour Z Green', gen:'Tour Z', year:2025,
    weights:[60,70,80], flexes:['M3','M4','M5'], price:475,
    launch:3, spin:2, torque:3.0, tip:4, mid:3, butt:3, balance:3, feel:5, stability:5,
    tags:['Mid launch','Low-mid spin','Tour stable'],
    bestFor:'Players wanting a mid flight with genuine tour stability and feel.',
    blurb:'The mid-launch Tour Z. Slightly lower torque than the Red for tour-level stability, paired with a smooth, connected load — a versatile fitter favorite across M3–M5.' },
  { id:'accra-shogun-red', mfr:'Accra', series:'Shogun', model:'Accra Shogun Red', gen:'Shogun', year:2026,
    weights:[60,70,80], flexes:['M4','M5'], price:550,
    launch:2, spin:1, torque:3.0, tip:5, mid:4, butt:4, balance:2, feel:4, stability:5,
    tags:['Low launch','Low spin','Max control'],
    bestFor:'Strong players prioritizing control and workability at low spin.',
    blurb:'The control-oriented Shogun. A genuinely stout tip (0.620" butt) delivers low launch, low spin, and maximum workability for faster tempos and aggressive transitions.' },
  { id:'accra-shogun-green', mfr:'Accra', series:'Shogun', model:'Accra Shogun Green', gen:'Shogun', year:2026,
    weights:[60,70,80], flexes:['M3','M4','M5'], price:550,
    launch:3, spin:3, torque:3.8, tip:3, mid:3, butt:3, balance:3, feel:5, stability:4,
    tags:['Mid launch','Mid spin','Premium feel'],
    bestFor:'Players wanting a balanced, do-everything build with premium feel.',
    blurb:'The balanced Shogun. Mid launch with medium spin and exceptional feel — the versatile, neutral profile of the line for a wide range of players.' },
  { id:'accra-shogun-blue', mfr:'Accra', series:'Shogun', model:'Accra Shogun Blue', gen:'Shogun', year:2026,
    weights:[40,50], flexes:['M0','M2','M4'], price:550,
    launch:5, spin:3, torque:3.9, tip:2, mid:2, butt:3, balance:3, feel:5, stability:3,
    tags:['Lightweight','High launch','Smooth tempo'],
    bestFor:'Smooth, deliberate tempos seeking maximum height and carry.',
    blurb:'The high-launch, lightweight (~45g) Shogun. Built in L/A/S (M0/M2/M4) flexes for smooth tempos chasing maximum height and carry distance.' },

  /* ================================== KBS =============================== */
  { id:'kbs-td', mfr:'KBS', series:'TD', model:'KBS TD', gen:'Tour Driven', year:2022,
    weights:[50,60,70,80], flexes:['R','S','X'], price:225,
    launch:3, spin:2, torque:3.4, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Low spin','Tunable'],
    bestFor:'Players wanting a versatile mid-launch, low-spin profile with KBS feel.',
    blurb:'A lighter, stiffer graphite driver shaft with the signature KBS feel — mid to mid-high launch with low spin and category tuning across weights.' },

  /* ================================ LA GOLF ============================= */
  { id:'lagolf-trono', mfr:'LA Golf', series:'Trono', model:'LA Golf Trono', gen:'Trono', year:2023,
    weights:[60,70,80], flexes:['S','X','TX'], price:550,
    launch:2, spin:2, torque:3.0, tip:4, mid:5, butt:3, balance:2, feel:3, stability:5,
    tags:['Low-mid launch','Low spin','Stiff mid'],
    bestFor:'Strong players wanting a stable, mid-stiff, penetrating flight.',
    blurb:'Developed with Bryson DeChambeau on LA Golf\'s 16-sided mandrel. The mid section is markedly stiffer than butt and tip, minimizing twist for a powerful, penetrating low-mid launch.' },
  { id:'lagolf-a-low', mfr:'LA Golf', series:'A-Series', model:'A-Series Low', gen:'A-Series', year:2024,
    weights:[60,70], flexes:['S','X'], price:500,
    launch:2, spin:2, torque:3.1, tip:4, mid:4, butt:3, balance:2, feel:3, stability:5,
    tags:['Low launch','Low spin','High speed'],
    bestFor:'High swing speeds wanting low launch and low spin.',
    blurb:'The low-launch profile of LA Golf\'s simplified fitting system. Built for high swing speeds that need to take launch and spin down.' },
  { id:'lagolf-a-mid', mfr:'LA Golf', series:'A-Series', model:'A-Series Mid', gen:'A-Series', year:2024,
    weights:[50,60,70], flexes:['R','S','X'], price:500,
    launch:3, spin:3, torque:3.3, tip:3, mid:3, butt:3, balance:3, feel:4, stability:4,
    tags:['Mid launch','Mid spin','Above-average speed'],
    bestFor:'Above-average swing speeds wanting a neutral, all-carbon profile.',
    blurb:'The neutral profile in LA Golf\'s A-Series. A smooth mid/mid all-carbon build for players with above-average swing speed.' },
  { id:'lagolf-a-high', mfr:'LA Golf', series:'A-Series', model:'A-Series High', gen:'A-Series', year:2024,
    weights:[40,50,60], flexes:['R','S'], price:500,
    launch:4, spin:3, torque:3.6, tip:2, mid:3, butt:3, balance:4, feel:4, stability:3,
    tags:['High launch','Mid spin','Lower speed'],
    bestFor:'Lower swing speeds wanting easy launch and carry.',
    blurb:'The high-launch A-Series. A softer, more active tip helps lower swing speeds get the ball up with all-carbon stability.' },

  /* ================================= OBAN =============================== */
  { id:'oban-kiyoshi-black', mfr:'Oban', series:'Kiyoshi', model:'Oban Kiyoshi Black', gen:'Kiyoshi', year:2019,
    weights:[50,60,70], flexes:['R','S','X'], price:425,
    launch:3, spin:3, torque:3.4, tip:3, mid:3, butt:3, balance:3, feel:5, stability:3,
    tags:['Mid launch','Mid spin','Japanese smooth'],
    bestFor:'Players who chase pure, smooth Japanese feel in a mid profile.',
    blurb:'A handcrafted Japanese profile prized for its silky, smooth load and balanced mid-launch flight.' },
  { id:'oban-revenge', mfr:'Oban', series:'Revenge', model:'Oban Revenge', gen:'Revenge', year:2023,
    weights:[50,60,70], flexes:['S','X'], price:425,
    launch:3, spin:3, torque:3.3, tip:3, mid:4, butt:3, balance:3, feel:5, stability:4,
    tags:['Mid launch','Mid spin','Stable & smooth'],
    bestFor:'Players wanting a firmer-mid Oban with added stability.',
    blurb:'A firmer-mid Oban that pairs the brand\'s smooth feel with extra stability for a controlled, repeatable mid flight.' },

  /* =============================== AUTOFLEX ============================= */
  { id:'autoflex-sf505', mfr:'Autoflex', series:'SF', model:'Autoflex SF505', gen:'SF', year:2021,
    weights:[40,50], flexes:['405','505','505x','505xx'], price:700,
    launch:5, spin:4, torque:4.5, tip:1, mid:2, butt:1, balance:5, feel:5, stability:1,
    tags:['Ultralight','Very high launch','Whippy'],
    bestFor:'Players chasing speed from an ultralight, ultra-active profile.',
    blurb:'The polarizing ultralight. A very active, whippy profile built to add clubhead speed — feel is everything and it is not for everyone.' },
];

/* ---- axes used by the radar visualization ---- */
const RADAR_AXES = [
  { key:'launch',    label:'Launch' },
  { key:'spin',      label:'Spin' },
  { key:'tip',       label:'Tip' },
  { key:'stability', label:'Stability' },
  { key:'feel',      label:'Smooth' },
  { key:'balance',   label:'Balance' },
];

/* ---- feature weights for the similarity engine ---- */
const FEATURE_WEIGHTS = {
  launch:1.0, spin:1.0, tip:1.0, mid:0.6, butt:0.6,
  balance:0.8, feel:0.7, stability:1.0,
};

/* ============================================================================
   REAL PRODUCT PHOTOS (hotlinked, shown on hover)
   Sourced from manufacturer / retailer CDNs (grips4less Shopify, truetemper).
   Add a line here to give any shaft a photo — the UI falls back to a branded
   colour swatch when an id is missing or a URL fails to load.
   ========================================================================== */
const SHAFT_IMAGES = {
  /* Fujikura — grips4less Shopify CDN */
  'fuji-ventus-blue':     'https://cdn.shopify.com/s/files/1/0095/7552/files/ventus-2024-blue_55b49156-1099-48c5-9228-29abb503d175.jpg?v=1753480081',
  'fuji-ventus-black':    'https://cdn.shopify.com/s/files/1/0095/7552/files/Ventus_Black_5-X_diag.jpg?v=1753479787',
  'fuji-ventus-red':      'https://cdn.shopify.com/s/files/1/0095/7552/files/Fujikura_Ventus_Red_5-S-diag.jpg?v=1753480051',
  'fuji-ventus-tr-blue':  'https://cdn.shopify.com/s/files/1/0095/7552/files/2026-ventus-tr-blue-velocore.jpg?v=1775978992',
  'fuji-speeder-nx-blue': 'https://cdn.shopify.com/s/files/1/0095/7552/files/SpeederNX_blue-front-1700.jpg?v=1753480316',
  'fuji-speeder-nx-violet':'https://cdn.shopify.com/s/files/1/0095/7552/files/speeder-nx-violet-1700-zoom.jpg?v=1753480018',
  /* Mitsubishi — official mitsubishigolf.com store */
  'mitsu-diamana-wb':     'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Diamana-WD-v1.3.png?v=1705273403',
  'mitsu-diamana-rb':     'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Diamana-RB-v1.1.png?v=1735764707',
  'mitsu-diamana-bb':     'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Diamana-BB-v1.1.png?v=1705277399',
  'mitsu-tensei-1k-white':'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-TENSEI-1K-White-2026-v1.1.png?v=1778645543',
  'mitsu-tensei-1k-blue': 'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-TENSEI-1K-Blue-2026-v1.1.png?v=1778645775',
  'mitsu-tensei-1k-red':  'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-TENSEI-1K-Pro-Red-v1.4.png?v=1709786351',
  'mitsu-kaili-white':    'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Kaili-DW-White-CB-v1.1.png?v=1778817921',
  'mitsu-kaili-red':      'https://cdn.shopify.com/s/files/1/0730/5917/2649/files/MCA-MCA_Main-Shaft-Kaili-DW-Red-CB-v1.2.png?v=1778817877',
  /* Graphite Design — fairwayjockey Shopify CDN */
  'gd-ad-di':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/DIBlack.jpg?v=1738269976',
  'gd-ad-vf':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/Graphite-Design-Tour-AD-VF.png?v=1701282771',
  'gd-ad-iz':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/Graphite_Design_Tour_AD_IZ.jpg?v=1634336231',
  'gd-ad-ub':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/Graphite-Design-Tour-AD-UB-Shaft.png?v=1634335102',
  'gd-ad-cq':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/Graphite-Design-Tour-AD-CQ.png?v=1667246380',
  'gd-ad-fi':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/touradfiwood.jpg?v=1757700524',
  'gd-ad-xc':             'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/Graphite_Design_Tour_AD_XC.jpg?v=1634592636',
  /* Project X — official truetemper.com store */
  'px-titan-black':       'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/Titan_Black_45.png?v=1773766422',
  'px-titan-yellow':      'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/px_titan_yellow_45_00f0a758-9acc-4109-b1c2-1b60bc567a1b.png?v=1779308320',
  'px-denali-black':      'https://www.truetemper.com/cdn/shop/files/denali_frost_black_web.png?v=1773076138&width=1206',
  'px-denali-blue':       'https://www.truetemper.com/cdn/shop/files/denali_frost_blue_web_3c3626ce-1ab6-402f-bed7-c8cc85229b35.png?v=1773076255&width=1206',
  'px-denali-red':        'https://www.truetemper.com/cdn/shop/files/denali_frost_web.png?v=1773076133&width=1206',
  'px-hzrdus-t1100':      'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/HZRDUS_T1100OC_45.png?v=1773766677',
  'px-hzrdus-black-g5':   'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/HZRDUS_G5Black_45.png?v=1773766997',
  'px-hzrdus-g5-yellow':  'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/px_g5yellow_45.png?v=1774997317',
  'px-cypher-20':         'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/Cypher_2.0_45.png?v=1773702373',
  /* Aldila — grips4less */
  'aldila-quaranta-gold': 'https://cdn.shopify.com/s/files/1/0095/7552/products/aldila-quaranta-gold-600_1597d8a1-691d-4c95-b5a1-0817699e763d.jpg',
  /* UST Mamiya — fairwayjockey */
  'ust-linq-blue':        'https://cdn.shopify.com/s/files/1/0561/5108/1146/files/LIN-QPCBlueCustom.png?v=1767815413',
  /* Accra — official truetemper.com store (per-model) */
  'accra-tour-z-red':     'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/ac_tz_red_45.png?v=1773698413',
  'accra-tour-z-green':   'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/ac_tz_green_45.png?v=1773698390',
  'accra-shogun-red':     'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/ac_shogun_red_45.png?v=1773700084',
  'accra-shogun-green':   'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/ac_shogun_green_45.png?v=1773700109',
  'accra-shogun-blue':    'https://cdn.shopify.com/s/files/1/0731/4063/3771/files/ac_shogun_blue_45.png?v=1773700127',
  /* LA Golf — fairwayjockey */
  'lagolf-trono':         'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/LAGP-Bryson-R1.png?v=1648492374',
  'lagolf-a-low':         'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/LA-Golf-LA-Series_40fc98ff-fcfb-4d89-be20-b3656e08ab40.png?v=1648708343',
  'lagolf-a-mid':         'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/LA-Golf-LA-Series_40fc98ff-fcfb-4d89-be20-b3656e08ab40.png?v=1648708343',
  'lagolf-a-high':        'https://cdn.shopify.com/s/files/1/0561/5108/1146/products/LA-Golf-LA-Series_40fc98ff-fcfb-4d89-be20-b3656e08ab40.png?v=1648708343',
  /* Autoflex — grips4less */
  'autoflex-sf505':       'https://cdn.shopify.com/s/files/1/0095/7552/files/autoflex-original-black.jpg?v=1761174225',
};

/* ---- representative paint-scheme colour for every shaft (fallback swatch + UI dot) ---- */
const SHAFT_COLORS = {
  'fuji-ventus-blue':'#2f6fb0','fuji-ventus-black':'#16181b','fuji-ventus-red':'#b22f2a',
  'fuji-ventus-white':'#dfe2e6','fuji-ventus-tr-blue':'#1d3f78','fuji-ventus-tr-black':'#0f1113',
  'fuji-speeder-nx-blue':'#2b6bce','fuji-speeder-nx-green':'#2e8b57','fuji-speeder-nx-violet':'#6b4fa0','fuji-speeder-nx-gold':'#c9a23a',
  'mitsu-diamana-wb':'#d9dde2','mitsu-diamana-rb':'#b83a3f','mitsu-diamana-bb':'#29487d',
  'mitsu-tensei-1k-white':'#e3e5e8','mitsu-tensei-1k-blue':'#245a9e','mitsu-tensei-1k-red':'#b23a35',
  'mitsu-kaili-white':'#dfe2e6','mitsu-kaili-blue':'#2766b3','mitsu-kaili-red':'#b3322c','mitsu-vanquish-green':'#3aa05a',
  'gd-ad-vr':'#1c2f5e','gd-ad-cq':'#3b3f46','gd-ad-fi':'#222a3a','gd-ad-di':'#26282d','gd-ad-iz':'#243a6b',
  'gd-ad-xc':'#4a2f6b','gd-ad-vf':'#6b1f2a','gd-ad-ub':'#b07a2a','gd-ad-gp':'#2e7d5b',
  'gd-ad-gc':'#2a2d3a','gd-ad-hd':'#26303a',
  'px-titan-black':'#141518','px-titan-yellow':'#c8a01e',
  'px-denali-black':'#1a1c1f','px-denali-blue':'#2a5fa0','px-denali-red':'#b13030',
  'px-hzrdus-t1100':'#0f1012','px-hzrdus-black-g5':'#161719','px-hzrdus-g5-yellow':'#d4b520','px-cypher-20':'#3a6ea5',
  'aldila-rogue-inf':'#3a3d44','aldila-rogue-silver':'#c8ccd2','aldila-quaranta-gold':'#c9a23a',
  'aldila-quaranta-sapphire':'#1f4e8c','aldila-nv-green':'#2e7d4f','aldila-ascent-ul':'#c2502a',
  'ust-linq-pc-white':'#dfe2e6','ust-linq-blue':'#234e86','ust-linq-pc-red':'#b23030',
  'ust-helium':'#7fb53a','ust-proforce-v2':'#2a4d7a',
  'accra-tour-z-red':'#b3322c','accra-tour-z-green':'#2e7d4f',
  'accra-shogun-red':'#a8302a','accra-shogun-green':'#2f8b56','accra-shogun-blue':'#2a5fa0','kbs-td':'#2a2d33',
  'lagolf-trono':'#b8932f','lagolf-a-low':'#1a1c1f','lagolf-a-mid':'#3a3d44','lagolf-a-high':'#b0b3b8',
  'oban-kiyoshi-black':'#15171a','oban-revenge':'#2a2d33','autoflex-sf505':'#d65a2a',
};

/* ---- VERIFIED published specs (real manufacturer numbers) for select models ----
   Shafts not listed here display their relative profile only, marked "est." ---- */
const SHAFT_SPECS = {
  'fuji-ventus-white':{ length:'46"', weight:'49–50g', torque:'5.0°', tip:'0.335"', butt:'0.602"', launch:'High', spin:'Mid-High' },
  'fuji-ventus-blue': { length:'46"', weight:'58–94g', torque:'2.8–3.9°', tip:'0.335"', butt:'0.602"', launch:'Mid', spin:'Low-Mid' },
  'fuji-ventus-black':{ length:'46"', weight:'80–93g', torque:'2.8–3.5°', tip:'0.335"', butt:'0.602"', launch:'Low', spin:'Low' },
  'fuji-ventus-red':  { length:'46"', weight:'59–94g', torque:'2.8–3.8°', tip:'0.335"', butt:'0.602"', launch:'Mid-High', spin:'Mid' },
  'gd-ad-fi':         { length:'46"', weight:'49–85g', torque:'2.6–5.3°', tip:'0.335"', butt:'0.598–0.608"', launch:'Mid', spin:'Low / Low-Mid' },
  'gd-ad-gc':         { length:'46"', weight:'~40–80g', torque:'2.5–5.5°', tip:'0.335"', butt:'0.602–0.608"', launch:'Mid', spin:'Low-Mid / Mid' },
  'gd-ad-hd':         { length:'46"', weight:'~40–80g', torque:'2.6–5.8°', tip:'0.335"', butt:'0.596–0.604"', launch:'Mid', spin:'Low / Low-Mid' },
  'px-denali-black':  { length:'46"', weight:'66–86g', torque:'2.8–3.6°', tip:'0.335"', butt:'0.600"', launch:'Low', spin:'Low' },
  'px-denali-blue':   { length:'46"', weight:'58–78g', torque:'2.7–4.5°', tip:'0.335"', butt:'0.600"', launch:'Mid', spin:'Mid' },
  'px-denali-red':    { length:'46"', weight:'48–65g', torque:'4.9–5.4°', tip:'0.335"', butt:'0.600"', launch:'High', spin:'Mid-High' },
  'px-titan-black':     { length:'46"', weight:'66–85g', torque:'2.7–3.5°', tip:'0.335"', butt:'0.600"', launch:'Low', spin:'Low' },
  'px-titan-yellow':    { length:'46"', weight:'66–81g', torque:'2.7–3.5°', tip:'0.335"', butt:'0.600"', launch:'Low', spin:'Low', note:'Counterbalanced' },
  'px-hzrdus-t1100':    { length:'46"', weight:'65–87g', torque:'2.3–2.4°', tip:'0.335"', butt:'0.605"', launch:'Low', spin:'Low', note:'Flexes 6.0 / 6.5' },
  'px-hzrdus-black-g5': { length:'46"', weight:'65–85g', torque:'2.7–3.5°', tip:'0.335"', butt:'0.600"', launch:'Low', spin:'Low' },
  'px-hzrdus-g5-yellow':{ length:'46"', weight:'64–83g', torque:'2.9–3.4°', tip:'0.335"', butt:'0.610"', launch:'Low', spin:'Low' },
  'px-cypher-20':       { length:'45–46"', weight:'47–57g', torque:'4.2–7.1°', tip:'0.335"', butt:'0.595–0.605"', launch:'Mid-High', spin:'Low-Mid' },
  'autoflex-sf505':   { length:'45"', weight:'~50g (505)', torque:'—', tip:'0.335"', butt:'0.600"', launch:'High', spin:'Mid-High', note:'Club-speed band: 95–100 mph (SF505)' },
  'accra-tour-z-red':   { length:'46"', weight:'53–105g', torque:'3.5°', tip:'0.335"', butt:'0.610"', launch:'Low', spin:'Low', note:'Flexes M3–M5' },
  'accra-tour-z-green': { length:'46"', weight:'52–95g', torque:'2.8–3.0°', tip:'0.335"', butt:'0.605"', launch:'Mid', spin:'Low-Mid', note:'Flexes M3–M5' },
  'accra-shogun-red':   { length:'46"', weight:'63–80g', torque:'3.0–3.1°', tip:'0.335"', butt:'0.620"', launch:'Low', spin:'Low', note:'Flexes M4–M5' },
  'accra-shogun-green': { length:'46"', weight:'54–80g', torque:'3.5–4.0°', tip:'0.335"', butt:'0.610–0.615"', launch:'Mid', spin:'Mid', note:'Flexes M3–M5' },
  'accra-shogun-blue':  { length:'46"', weight:'43–48g', torque:'3.8–4.0°', tip:'0.335"', butt:'0.610"', launch:'High', spin:'Mid', note:'Flexes M0(L)/M2(A)/M4(S)' },
  'aldila-rogue-inf':       { length:'46"', weight:'57–84g', torque:'3.1–4.6°', tip:'0.335"', butt:'0.640–0.651"', launch:'Mid', spin:'Mid-Low', note:'Flexes TR/TS/TX' },
  'aldila-rogue-silver':    { length:'46"', weight:'60–73g', torque:'2.9–3.5°', tip:'0.335"', butt:'0.598–0.606"', launch:'Low-Mid', spin:'Low-Mid' },
  'aldila-quaranta-gold':   { length:'46"', weight:'35–55g', torque:'5.1–7.5°', tip:'0.335"', butt:'0.588–0.602"', launch:'Mid', spin:'Mid' },
  'aldila-quaranta-sapphire':{ length:'46"', weight:'47–56g', torque:'4.6–5.1°', tip:'0.335"', butt:'0.598–0.608"', launch:'Mid', spin:'Mid' },
  'aldila-nv-green':        { length:'46"', weight:'55–85g', torque:'2.8–4.5°', tip:'0.335"', butt:'0.620–0.636"', launch:'Low', spin:'Low' },
  'aldila-ascent-ul':       { length:'46"', weight:'41–48g', torque:'8.0–8.5°', tip:'0.335"', butt:'0.598–0.604"', launch:'High', spin:'Mid-High' },
  'ust-linq-pc-white':      { length:'46"', weight:'65–88g', torque:'2.9–3.7°', tip:'0.335"', launch:'Low', spin:'Low' },
  'ust-linq-blue':          { length:'46"', weight:'56–78g', torque:'3.1–4.3°', tip:'0.335"', launch:'Mid', spin:'Low' },
  'ust-linq-pc-red':        { length:'46"', weight:'57–77g', torque:'3.1–3.9°', tip:'0.335"', launch:'High', spin:'Low' },
  'ust-helium':             { length:'46"', weight:'44–56g', torque:'6.0–6.2°', tip:'0.335"', launch:'High', spin:'High', note:'Counterbalanced' },
  'ust-proforce-v2':        { length:'46"', weight:'51–90g', torque:'1.8–5.1°', tip:'0.335"', butt:'0.600–0.610"', launch:'Mid', spin:'Low' },
};

/* ============================================================================
   EXACT TORQUE BY WEIGHT-CLASS × FLEX (real manufacturer spec tables)
   ----------------------------------------------------------------------------
   torqueAt(id, weight, flex) returns the exact value for a selected build;
   if that combo isn't in the table it falls back to the same flex at the
   nearest weight, and finally to the shaft's representative `torque` field.
   Keys: weight class (g) → flex code → torque (degrees).
   ========================================================================== */
const SHAFT_TORQUE = {
  /* Graphite Design — full weight×flex grid (proschoicegolfshafts) */
  'gd-ad-fi': { 40:{R2:5.3,R1:5.3,S:5.2,X:5.2}, 50:{R2:4.6,R1:4.5,S:4.5,X:4.5}, 60:{SR:3.2,S:3.2,X:3.2,TX:3.2}, 70:{S:2.9,X:2.9,TX:2.9}, 80:{X:2.6} },
  'gd-ad-di': { 50:{R:4.7,S:4.6,X:4.6}, 60:{S:3.3,X:3.3,TX:3.3}, 70:{S:3.2,X:3.1,TX:3.1}, 80:{S:3.0,X:2.9,TX:2.9} },
  'gd-ad-iz': { 50:{R:4.5,S:4.4,X:4.4}, 60:{S:3.2,X:3.2,TX:3.2}, 70:{S:3.1,X:3.1,TX:3.0}, 80:{S:2.9,X:2.9} },
  'gd-ad-vr': { 40:{R2:5.7,R1:5.6,S:5.6}, 50:{R2:4.5,R1:4.5,S:4.5,X:4.5}, 60:{SR:3.2,S:3.2,X:3.2}, 70:{S:3.0,X:3.0}, 80:{S:2.6,X:2.6} },
  'gd-ad-gc': { 40:{R2:5.5,R1:5.5,S:5.5}, 50:{R2:4.5,R1:4.5,S:4.5,X:4.4}, 60:{SR:3.1,S:3.1,X:3.1,TX:3.1}, 70:{S:2.8,X:2.8,TX:2.8}, 80:{X:2.5} },
  'gd-ad-hd': { 40:{R2:5.8,R1:5.8,S:5.7}, 50:{R2:4.6,R1:4.5,S:4.5,X:4.5}, 60:{SR:3.0,S:3.0,X:3.0,TX:3.0}, 70:{S:2.8,X:2.8,TX:2.8}, 80:{S:2.6,X:2.6} },
  'gd-ad-xc': { 50:{S:4.2,X:4.2}, 60:{S:3.2,X:3.2,TX:3.2}, 70:{S:3.0,X:3.0,TX:3.0}, 80:{S:2.8,X:2.8} },
  'gd-ad-vf': { 50:{S:4.3,X:4.3}, 60:{S:3.3,X:3.3,TX:3.3}, 70:{S:3.0,X:3.0,TX:3.0}, 80:{X:2.8} },
  'gd-ad-ub': { 40:{R:5.5,S:5.5}, 50:{R:4.4,S:4.4,X:4.4}, 60:{S:3.2,X:3.2}, 70:{S:3.0,X:3.0} },
  'gd-ad-cq': { 40:{R:6.0,S:6.0}, 50:{R:4.6,S:4.5,X:4.5}, 60:{SR:3.4,S:3.4,X:3.4}, 70:{S:3.2,X:3.2} },

  /* Project X — by flex (truetemper.com); nearest-flex fallback covers weights */
  'px-titan-black':      { 60:{'5.5':3.5,'6.0':3.5,'6.5':3.3,'TX':2.7} },
  'px-titan-yellow':     { 60:{'5.5':3.5,'6.0':3.5,'6.5':3.3,'TX':2.7} },
  'px-denali-black':     { 60:{'6.0':3.6,'6.5':3.5,'TX':2.8} },
  'px-denali-blue':      { 50:{'6.0':4.5,'6.5':3.6,'TX':2.7} },
  'px-denali-red':       { 40:{'5.0':5.4,'5.5':5.2,'6.0':4.9} },
  'px-hzrdus-t1100':     { 60:{'6.0':2.4,'6.5':2.3} },
  'px-hzrdus-black-g5':  { 60:{'5.5':3.5,'6.0':3.2,'6.5':3.0,'TX':2.7} },
  'px-hzrdus-g5-yellow': { 60:{'5.5':3.4,'6.0':3.2,'6.5':3.0,'TX':2.9} },
  'px-cypher-20':        { 40:{'4.0':7.1,'5.0':6.0,'5.5':5.3,'6.0':4.2} },

  /* Accra — truetemper.com (torque uniform by flex) */
  'accra-tour-z-red':   { 60:{M3:3.5,M4:3.5,M5:3.5}, 70:{M3:3.5,M4:3.5,M5:3.5}, 80:{M3:3.5,M4:3.5,M5:3.5} },
  'accra-tour-z-green': { 60:{M3:3.0,M4:3.0,M5:2.8}, 70:{M3:3.0,M4:3.0,M5:2.8}, 80:{M3:3.0,M4:3.0,M5:2.8} },
};
